# fly.toml app configuration file generated for sleep4android2tuya on 2023-06-12T18:48:23-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "sleep4android2tuya"
primary_region = "eze"

[env]
  PORT = "8080"
  
[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
